= run-cpt
:toc: preamble

[link=https://github.com/grisumbras/run-cpt/actions]
image::https://github.com/grisumbras/run-cpt/workflows/Build/badge.svg?branch=master[Build status]

____
GitHub Action that runs conan_package_tools
____

== Usage
Example usage:

[source,yaml]
----
uses: grisumbras/run-cpt@latest
with:
  build-script: conan/build.py
----

You can set environment variables that control Conan and CPT behaviour using
`env` key:

[source,yaml]
----
- uses: grisumbras/run-cpt@latest
  env:
    CONAN_REMOTES: https://api.bintray.com/conan/bincrafters/public-conan
----

Additionally, if `CONAN_USERNAME` is not specified, the first part of
`GITHUB_REPOSITORY` (before slash) will be used.

=== Inputs
build-script::
Path to the build script. Given `build-script: x/y/z.py`, the action will run
`python x/y/z.py`. `build.py` by default.
install::
Install conan_package_tools before running the build script if the value is not
`no`. If the value is `latest` install the latest version, otherwise install
the version equal to that value. `latest` by default.

The following parameters allow you to customize conan and conan_package_tools behaviour.
It is conrolled by environment variables and there is no way to undefine a variable from
a workflow file after it was set. For example, you cannot set CONAN_DOCKER_IMAGE and
then unset it. This does not allow you to use strategy.matrix to run several jobs
based on a single job description. With the following parameters you can setup the behaviour
without using environment variables from a workflow file. The values of these parameters
override the values of the corresponding environment variables, so you can setup default
environment variables and modify the behaviour of a conan for some jobs/steps exclusively.

compiler::
Sets which compiler conan should use. Use this option in a combination with an option
`compiler-versions`. Defaults to an empty string, conan_package_tools will choose a compiler
based on environment variables in this case. Other supported values are:
* gcc
* apple_clang
* vs
compiler-versions::
**Required if `compiler` is set** While `compiler` option chooses which environment variable
to setup, this option sets its value:
* CONAN_GCC_VERSIONS
* CONAN_APPLE_CLANG_VERIONS
* CONAN_VISUAL_VERIONS
docker-image::
Overrides or clears CONAN_DOCKER_IMAGE environment variable. Set to an empty string to do nothing.
Set to 'clear' to undefine the environment variable. Defaults to an empty string.

== Maintainer
Dmitry Arkhipov <grisumbras@gmail.com>

== Contributing
Patches welcome!

== License
link:LICENSE[BSL-1.0] (C) 2019 Dmitry Arkhipov
